# This is a basic GitHub Action workflow to run a cURL command.
#
# To use this file:
# 1. Create a directory named `.github/workflows` in the root of your repository if it doesn't already exist.
# 2. Create a new file inside that directory, for example, `curl-request.yml`.
# 3. Copy and paste the code below into the new file.
# 4. Customize the `curl` command in the "Run cURL" step to your specific needs.
# 5. Commit and push the file to your repository.

# Name of the workflow, which will be displayed in the "Actions" tab of your GitHub repository.
name: Run cURL Command

# Controls when the workflow will run.
on:
  # Triggers the workflow on push events but only for the "main" branch.
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel.
jobs:
  # This workflow contains a single job called "curl_request_job".
  curl_request_job:
    # The type of runner that the job will run on.
    # 'ubuntu-latest' is a good general-purpose choice.
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job.
    steps:
      # This step runs the cURL command.
      - name: Run cURL Request
        run: curl -X POST "${{ secrets.VERCEL_TARGET_URL }}"
